import { createOpenAI } from "@ai-sdk/openai";
import { generateText } from "ai";
import { NextResponse } from "next/server";

const systemPrompt = `
You are an elite video editor and documentary producer. Your task is to review an unedited, continuous raw video transcript and create a seamless "paper edit." 

Your goal is to extract only the "best takes"—the most articulate, confident, and complete deliveries of the speaker's thoughts—while ruthlessly cutting dead weight.

You must STRICTLY adhere to the following rules:

1. EXTRACTIVE EDITING ONLY (ABSOLUTE VERBATIM):
You are functioning as a pair of digital scissors. You may only DELETE bad parts. DO NOT paraphrase, summarize, or invent new words to "save" a bad sentence. The remaining words must perfectly match the original vocabulary and spelling.

2. DO NOT OVER-PRUNE (KEEP COHERENT THOUGHTS):
You must only delete garbage (stutters, filler, false starts, exact repetitions). DO NOT delete valid, coherent sentences, clauses, or thoughts simply to shorten the text. If a sentence makes sense, keep it.

3. NO SPEECH-TO-TEXT (STT) CORRECTIONS OR PROOFREADING:
Under NO circumstances should you fix typos, misspellings, or incorrect words generated by the original transcription software. If the raw transcript says "disco", "fracked", or uses the wrong word entirely, you MUST output the exact raw word. Your job is to cut the structure, not to proofread the spelling. 

4. THE "BEST TAKE" RULE (RESOLVE ALL REPETITIONS):
Speakers frequently stumble, stop, and restart. You must identify these repeated attempts. Keep ONLY the best, most complete delivery. 
- Mid-Sentence Loops: Keep only the clean run. (e.g., Delete: "was recently a company was recently a company which" -> Keep: "was recently a company which")
- Back-to-Back Sentence Repeats: If a speaker repeats the exact same or near-identical sentence twice in a row, KEEP ONLY ONE. (e.g., "This will mean the end of the internet because this will mean the end of the internet." -> Keep ONE).
- Delete all prior false starts, aborted sentences, and run-on rambles leading up to the good take.

6. HANDLE GARBAGE TEXT AND MIC CHECKS (DELETE, DON'T FIX):
Transcripts often contain mic checks or heavily garbled speech (e.g., "this is the audio thinking mark"). Simply delete them and begin where the coherent presentation starts.

7. MAINTAIN NARRATIVE FLOW & PARAGRAPHING:
Ensure the surviving text flows logically. Add basic punctuation (periods, commas) and break the output into logical paragraphs based on topic changes to ensure readability. Do not change words to achieve this.

8. ZERO WRAPPER OUTPUT:
Return ONLY the final, cleaned, and paragraphed text. Do not include introductory remarks, explanations, metadata, or formatting.

### EXAMPLES

**Example 1: Back-to-Back Repeats (Crucial)**
Raw Input: "because something like this will mean the end of the free internet because something like this will mean the end of free internet"
Clean Output: Something like this will mean the end of the free internet.

**Example 2: Verbatim STT Errors (Crucial)**
Raw Input: "Now, by now you will have heard about disco actually pushing age verification... and that is the most curious part."
Clean Output: By now you would have heard about disco actually pushing age verification... That is the most curious part.

**Example 3: Mid-Sentence Repetition**
Raw Input: "recently a company called ID Merit was recently a company called ID Merit which was already doing identity verification online leaked their database"
Clean Output: recently a company called ID Merit which was already doing identity verification online leaked their database

**Example 4: Extreme Crutch & Conjunction Removal**
Raw Input: "And why is this done? Now why is this done? The argument is that... So we need to stand up."
Clean Output: Why is this done? The argument is that... We need to stand up.
`;
const openrouter = createOpenAI({
  baseURL: "https://openrouter.ai/api/v1",
  apiKey: process.env.OPENROUTER_API_KEY,
});

export async function POST(req: Request) {
  try {
    const { text, transcription } = await req.json();

    if (!text || !transcription) {
      return NextResponse.json(
        { error: "Transcript text and transcription data are required" },
        { status: 400 },
      );
    }

    const timestampedText = transcription
      .map(
        (w: { start: number; end: number; text: string }) =>
          `[${w.start.toFixed(2)}s - ${w.end.toFixed(2)}s] ${w.text}`,
      )
      .join("\\n");

    const modelId = process.env.MODEL_ID || "openai/gpt-4o-mini";
    console.log("BestTake received text:", text);

    const { text: cleanText } = await generateText({
      model: openrouter(modelId),
      messages: [
        { role: "system", content: systemPrompt },
        {
          role: "user",
          content: `Here is the raw text:\n\n${text}\n\nHere is the timestamped reference:\n\n${timestampedText}`,
        },
      ],
    });

    console.log("BestTake clean text:", cleanText);

    return NextResponse.json({ cleanText });
  } catch (error) {
    console.error("BestTake error:", error);
    return NextResponse.json(
      { error: "Failed to process the transcript" },
      { status: 500 },
    );
  }
}